### ISSUE TITLE
Test IBC on Mocha

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#5372]
## Context

celestia-app v4 broke IBC because it didn't register the IBC capability module. See https://github.com/celestiaorg/celestia-app/issues/5340 which was fixed in https://github.com/celestiaorg/celestia-app/pull/5344 and included in:
- v5.0.1-arabica
- v5.0.1-mocha

## Problem

I verified the IBC fix on a local devnet.

## Proposal

Test that IBC works on Mocha after the v5 activation height. Ideally we use a connection that already exists.

**Comment by rootulp** [comment]
- We can test IBC on testnets using https://testnet.go.skip.build/
- go.skip.build generates a tx with too low of a fee so you must configure the tx to use high fee
- Verified that this [tx](https://www.mintscan.io/celestia-testnet/tx/786661D6177C0C69AE165452570F91F54A3878359B8D344A3F147F611740D404?height=7401038) for an IBC transfer from Mocha to Stride testnet hit `failed to execute message; message index: 0: module does not own channel capability: channel capability not found`
- Will re-test after v5 activates on Mocha

**Comment by rootulp** [comment]
v5 just activated on Mocha but I can't use https://testnet.go.skip.build/ to send a tx any more. It just hangs after clicking "Confirm" likely because the RPC endpoint that it uses didn't upgrade in time.

**Comment by mindstyle85** [comment]
if it was our rpc then it should work now

ours was stuck on v4 like the multiplexer didnt switch to v5 until i restarted it (mentioned it on slack too)

**Comment by rootulp** [comment]
IBC transfer before v5 activation height failed: https://testnet.celestia.explorers.guru/transaction/786661D6177C0C69AE165452570F91F54A3878359B8D344A3F147F611740D404?height=7401038
IBC transfer after v5 activation height succeeds: https://testnet.celestia.explorers.guru/transaction/4E0F6DB9661306A822C13B7FE23FC70756A4CAD35796A2AA29648A82E4AF8CBD?height=7401360

**Comment by rootulp** [comment]
I was only able to test that the tx landed on Celestia. I couldn't test an end to end IBC transfer because I wasn't getting relayed.

It would be nice to verify that I can bridge utia from Celestia -> Neutron and then back from Neutron -> Stride. To do that, I need to set up a relayer that relays on that connection.

**Comment by rootulp** [comment]
I confirmed that I could send utia from Mocha -> Neutron ~and back.~

1. Created [Hermes config](https://gist.github.com/rootulp/255d24c19ace5dee750905c8ab90b201). I had to fiddle with RPC, GRPC, WS endpoints to get reliable ones for both chains. Then had to bump gas numbers to avoid out of gas errors.
3. Created keys for Celestia and Neutron
4. Got both keys funded
5. Import both keys into Hermes
6. Start relayer
7. Create a new connection between Mocha and Neutron: https://pastebin.com/sDfeJD5J
8. Then transferred utia from Mocha to Neutron and back: https://pastebin.com/eeBZiLkc

Mintscan proof:
1. Send 1 utia from Mocha to Neutron: https://www.mintscan.io/celestia-testnet/tx/A9BA1A66E28236C39B80B30CE37BC53F377DFC381D6E1279FD811F636F46163E?height=7403356
2. Receipt on Neutron: https://www.mintscan.io/neutron-testnet/tx/2826B3A60CEAA4D71FEBE38F39D8886677A5A61656FCCD542C9FC592CC96A92E?height=33746531
3. Send 1 utia from Neutron to Mocha: https://www.mintscan.io/neutron-testnet/tx/7C9E08CB89A8B3B5B6EF07B7CE7AFEE26EF0D121A7F5C8731DD5DA4CC2068A9E?height=33746698
4. Receipt on Mocha: TBD I don't see it yet

**Comment by rootulp** [comment]
I still don't see the utia that I sent from Neutron back on Mocha. I've tried a few more txs they're not landing on Mocha. No relevant error logs in Hermes.

Update: reasonably confident my relayer stopped working and idk why.

**Comment by rootulp** [comment]
Thank god there is some third party relayer running on Mocha <> Stride.

Sent utia from Mocha to Stride testnet: 
- https://www.mintscan.io/celestia-testnet/tx/F5158A09248DA877AFFCF533F9B00437B07434E78735FF54F495044F2BE36633

Sent utia from Stirde testnet to Mocha: 
- https://www.mintscan.io/celestia-testnet/tx/A1C5EC1D7AB7459055490F39288ACC36A549F947AFA594B4F9A9D765AFC07BCC
